### ISSUE TITLE
Irrelevant question (regarding SFAuthorization in macOS)

### ISSUE THREAD

**Issue by spieglt** [topnotcher/eagle-library#1]
Hi Greg,
I have a question about your answer here: https://stackoverflow.com/questions/28096630/mac-os-x-10-10-reorder-preferred-networks/
Sorry to bother you with this here, it won't let me comment on SO as I don't have enough reputation and the only link on your profile was to your Github. How, in that sample, did you know to use the string `"system.preferences"` in the call to `obtainWithRight`? Is that documented somewhere? Thanks.

**Comment by topnotcher** [comment]
I have no idea. I only know it involved massive amounts of googling and trial/error. That was my first and (so far/hopefully) last experience with OS X development.

**Comment by spieglt** [comment]
Thanks. I'm in the massive amounts of googling phase. The docs for that function just say it takes an AuthorizationString, but that's just a UTF-8 string and there's no reference to what values are meaningful. 
https://developer.apple.com/documentation/securityfoundation/sfauthorization/1417652-obtainwithright

**Comment by spieglt** [comment]
If you're ever curious about this again, I did find where the magic string came from and asked Apple about the situation here, though they never responded. Thanks again for your response. https://forums.developer.apple.com/thread/96740
